#logging:
#  file: argoIntegrator
#  path: /apps/OpsERA/logs/components/argo-integrator
server:
  port: 9092

---

spring:
  profiles: dev
  application:
    name: argo-integrator
    description: API for integrating with Argo Tool
pipeline:
  config:
#    baseurl: http://microservices-dev.opsera.io:9091/api/pipeline
     baseurl: http://localhost:8071
vault:
  config:
    baseurl: http://microservices-dev.opsera.io:9091/api/vault/
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://microservices-dev.opsera.io:8761/eureka/

---

spring:
  profiles: test
  application:
    name: argo-integrator
    description: API for integrating with Argo Tool
pipeline:
  config:
    baseurl: http://10.0.3.253:9091/api/pipeline
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://10.0.3.253:8761/eureka/

---

spring:
  profiles: prod
  application:
    name: argo-integrator
    description: API for integrating with Argo Tool
pipeline:
  config:
    baseurl: http://10.0.2.4:9091/api/pipeline
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://10.0.2.4:8761/eureka/
