logging:
  file: 
    name: argoIntegrator
    path: /apps/OpsERA/logs/components/argo-integrator
server:
  port: 9096
  shutdown: graceful
spring:
  application:
    name: argo-integrator
    description: API for integrating with Argo Tool
  lifecycle:
    timeout-per-shutdown-phase: 2h
  task:
    execution:
      pool:
        core-size: 50
        queue-capacity: 100 
        max-size: 200
      shutdown:
        await-termination: true
        await-termination-period: 2h
      thread-name-prefix: ArgoAsyncThread-
kafka:
  consumer:
    autocommit.interval: 10
    concurrentcount: 3
  service:
    baseurl: ${opsera.config.baseurl}/api/kafka

pipeline:
  config:
    baseurl: ${opsera.config.baseurl}/api/pipeline
vault:
  config:
    baseurl: ${opsera.config.baseurl}/api/vault
customer:
  config:
    baseurl: ${opsera.config.baseurl}/api/customer 
aws:
  service:
    baseurl: ${opsera.config.baseurl}/api/aws
azure:
  service:
    baseurl: ${opsera.config.baseurl}/api/azure
argo:
  defaultUrl: https://ivt-argo.opsera.io/
  
---

spring:
  profiles: kubernetes
kafka:
  bootstrapServer: ${OPSERA_KAFKA_BOOTSTRAP_URL:aeb8153aa1fc74089bd33608cc2d5e60-0a9b5f33d78b35f5.elb.us-east-2.amazonaws.com:9094}
  consumer:
    groupId: argo-kubernetes-group   
opsera:
  config:
    baseurl: ${OPSERA_API_SERVICE_URL:https://apigateway.opsera-test-private.opsera.io}
