logging:
  file: argoIntegrator
  path: /apps/OpsERA/logs/components/argo-integrator
server:
  port: 9096
spring:
 application:
    name: argo-integrator
    description: API for integrating with Argo Tool
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

---

spring:
  profiles: dev
pipeline:
  config:
    baseurl: http://microservices-dev.opsera.io:9091/api/pipeline
vault:
  config:
    baseurl: http://microservices-dev.opsera.io:9091/api/vault
argo:
  defaultUrl: https://ivt-argo.opsera.io/
eureka:
  client:
    serviceUrl:
      defaultZone: http://microservices-dev.opsera.io:8761/eureka/

---

spring:
  profiles: test
pipeline:
  config:
    baseurl: https://microservice.internal.opsera.io/api/pipeline
vault:
  config:
    baseurl: https://microservice.internal.opsera.io/api/vault
argo:
  defaultUrl: https://ivt-argo.opsera.io/
eureka:
  client:
    serviceUrl:
      defaultZone: https://microservice.internal.opsera.io:8761/eureka/

---

spring:
  profiles: prod
pipeline:
  config:
    baseurl: https://microservice.internal.opsera.io/api/pipeline
vault:
  config:
    baseurl: https://microservice.internal.opsera.io/api/vault
argo:
  defaultUrl: https://ivt-argo.opsera.io/
eureka:
  client:
    serviceUrl:
      defaultZone: https://microservice.internal.opsera.io:8761/eureka/
      
---

spring:
  profiles: freetrial
pipeline:
  config:
    baseurl: https://freetrial-microservice.opsera.io/api/pipeline
vault:
  config:
    baseurl: https://freetrial-microservice.opsera.io/api/vault
argo:
  defaultUrl: https://ivt-argo.opsera.io/
eureka:
  client:
    serviceUrl:
      defaultZone: https://freetrial-microservice.opsera.io:8761/eureka/

