logging:
  file: 
    name: argoIntegrator
    path: /apps/OpsERA/logs/components/argo-integrator
server:
  port: 9096
  shutdown: graceful
spring:
 application:
    name: argo-integrator
    description: API for integrating with Argo Tool
 lifecycle:    timeout-per-shutdown-phase: 2h

---

spring:
  profiles: freetrial
pipeline:
  config:
    baseurl: https://freetrial-microservice.opsera.io/api/pipeline
vault:
  config:
    baseurl: https://freetrial-microservice.opsera.io/api/vault
customer:
  config:
    baseurl: https://freetrial-microservice.opsera.io/api/customer
argo:
  defaultUrl: https://ivt-argo.opsera.io/

---

spring:
  profiles: kubernetes
pipeline:
  config:
    baseurl: http://opsera-apigateway.microservices.svc.cluster.local:9091/api/pipeline
vault:
  config:
    baseurl: http://opsera-apigateway.microservices.svc.cluster.local:9091/api/vault
customer:
  config:
    baseurl: http://opsera-apigateway.microservices.svc.cluster.local:9091/api/customer    
argo:
  defaultUrl: https://ivt-argo.opsera.io/
