logging:
  file: 
    name: argoIntegrator
    path: /apps/OpsERA/logs/components/argo-integrator
server:
  port: 9096
  shutdown: graceful
spring:
  application:
    name: argo-integrator
    description: API for integrating with Argo Tool
  lifecycle:
    timeout-per-shutdown-phase: 2h

pipeline:
  config:
    baseurl: ${opsera.config.baseurl}/api/pipeline
vault:
  config:
    baseurl: ${opsera.config.baseurl}/api/vault
customer:
  config:
    baseurl: ${opsera.config.baseurl}/api/customer 
aws:
  service:
    baseurl: ${opsera.config.baseurl}/api/aws
azure:
  service:
    baseurl: ${opsera.config.baseurl}/api/azure
argo:
  defaultUrl: https://ivt-argo.opsera.io/
---

spring:
  profiles: kubernetes
   
opsera:
  config:
    baseurl: ${OPSERA_API_SERVICE_URL:http://opsera-apigateway.microservices.svc.cluster.local:9091}
